name: plateful
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.0.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_messaging: ^15.2.10
  google_fonts: ^6.1.0
  provider: ^6.1.1
  lottie: ^3.3.1
  glass_kit: ^4.0.1
  animated_text_kit: ^4.2.2
  animations: ^2.0.8
  flutter_neumorphic_plus: ^3.4.0
  js: ^0.7.2
  firebase_storage: ^12.4.10
  google_sign_in: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  syncfusion_flutter_charts: ^30.1.40
  syncfusion_flutter_core: ^30.1.40
  qr_flutter: ^4.1.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.0
  confetti: ^0.7.0
  flutter_slidable: ^3.1.1
  flutter_rating_bar: ^4.0.1
  emoji_picker_flutter: ^1.6.4
  flutter_gl: ^0.0.2+2
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/food_lover.json
    - assets/animations/ai_platform.json
    - assets/animations/restaurant.json
    - assets/images/hero_food_bg.jpg
    - assets/images/how_it_works_bg.jpg
    - assets/images/features_bg.jpg
    - assets/images/community_bg.jpg
    - assets/animations/
    - assets/images/
    - assets/icons/
    
  # Fonts are loaded via Google Fonts package
