name: plateful
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.17.0
  firebase_auth: ^4.15.0   # Compatible with ^2.17.0 firebase_core
  lottie: ^2.7.0
  glass_kit: ^2.0.1
  flutter_neumorphic_plus: ^3.4.0
  animated_text_kit: ^4.2.2
  google_fonts: ^6.1.0
  animations: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
