// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0QfAhNXZGO7mqDZcVzlEFYaJqp9RAhuA',
    appId: '1:1009788777874:web:376cde409e62a0ed0a7d4b',
    messagingSenderId: '1009788777874',
    projectId: 'plateful-8c60b',
    authDomain: 'plateful-8c60b.firebaseapp.com',
    storageBucket: 'plateful-8c60b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJo_b_7vXjrWY7qykLex98AiCN91MtK1Y',
    appId: '1:1009788777874:android:c57bcb5dc501ec3a0a7d4b',
    messagingSenderId: '1009788777874',
    projectId: 'plateful-8c60b',
    storageBucket: 'plateful-8c60b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQBCPXv5-8am1kBcGsx5ft0TanFM8Bh0c',
    appId: '1:1009788777874:ios:54c7df3b4bf57a6d0a7d4b',
    messagingSenderId: '1009788777874',
    projectId: 'plateful-8c60b',
    storageBucket: 'plateful-8c60b.firebasestorage.app',
    iosBundleId: 'com.example.plateful',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQBCPXv5-8am1kBcGsx5ft0TanFM8Bh0c',
    appId: '1:1009788777874:ios:54c7df3b4bf57a6d0a7d4b',
    messagingSenderId: '1009788777874',
    projectId: 'plateful-8c60b',
    storageBucket: 'plateful-8c60b.firebasestorage.app',
    iosBundleId: 'com.example.plateful',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0QfAhNXZGO7mqDZcVzlEFYaJqp9RAhuA',
    appId: '1:1009788777874:web:71e43174f7b5caa60a7d4b',
    messagingSenderId: '1009788777874',
    projectId: 'plateful-8c60b',
    authDomain: 'plateful-8c60b.firebaseapp.com',
    storageBucket: 'plateful-8c60b.firebasestorage.app',
  );
}
